name: actions workflow
on: push
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple js actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 #can also be a branch or commit\
        with:
          who-to-greet: Luis
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"