name: container

on:
  push:
    
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:17-alpine3.14
      # env, ports, volumes, options --hostname
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release

