name: containers
on: push

jobs:
  containers:
    runs-on: ubuntu-latest
    container:
      image: node:10
    steps:
      - name: log node v
        run: |
          node -v
      - name: step with container
        uses: docker://node:18-alpine
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: checkout
        uses: actions/checkout@v3
      - name: run a script
        uses: docker://node:18-alpine
        with:
          entrypoint: ./script.sh
          args: 'some string'
