name: matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: display node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: display node version
        run: node -v