name: matrix
on: pull_request

jobs:
  node-version:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        #  include:
        #     - is_ubuntu_8 = "true"
        #       os: ubuntu-latest
        #       node-version: 8

        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8

      max-parallel: 3
    runs-on: ${{matrix.os}}
    #env: IS_UBNTU_8 = ${{matrix.is_ubuntu_8}}
    steps:
      - name: display node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_verison}}
      - name: display node version
        run: node -v
