name: secretfile
on:
  - push

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}} 
      - name: print result
        run: |
          pwd
          ls -alh
          cat ~/secret.json