name: services
on: push
jobs:
  simple-app:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3000:3000

      mongo:
        image: mongo
        ports:
          - 27001:27001
    steps:
      - name: post a user
        run: |
          curl -X POST http://localhost:3000/api/user -H 'Content-Type: application/json' -d '{"username": "hello","address": "dwded"}'
      - name: get user
        run: |
          curl  http://localhost:3000/api/users